#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
allow() { "$repo/scripts/test-command-policy" bm "$1"; }
deny() { ! "$repo/scripts/test-command-policy" bm "$1"; }

allow "bm --help"
allow "bm --version"
allow "bm status --help"
allow "bm status --local"
allow "bm status --local --json"
allow "bm status --json --local"
allow "bm doctor --help"
allow "bm doctor --local"
allow "bm project --help"
allow "bm tool --help"
allow "command -v bm"
allow "pwd"

deny "bm status"
deny "bm status --json"
deny "bm status --verbose"
deny "bm status --cloud"
deny "bm doctor"
deny "bm doctor --cloud"
deny "bm reset"
deny "bm reset --yes"
deny "bm reindex"
deny "bm import markdown"
deny "bm format"
deny "bm update"
deny "bm mcp"
deny "bm cloud"
deny "bm schema"
deny "bm project list"
deny "bm project ls"
deny "bm project info"
deny "bm project add test ~/tmp"
deny "bm project remove test"
deny "bm project default test"
deny "bm project move test ~/tmp"
deny "bm project set-cloud test"
deny "bm project set-local test"
deny "bm tool read-note test"
deny "bm tool search-notes test"
deny "bm tool recent-activity"
deny "bm tool build-context"
deny "bm tool write-note test --content hello"
deny "bm tool edit-note test"
deny "bm --install-completion"
deny "bm --show-completion"
deny "bm status; cat ~/.basic-memory/config"
deny "bm status | cat"
deny "bm status > /tmp/bm-status.txt"
deny "env"
deny "cat ~/.basic-memory/config"
