#!/bin/sh
set -eu

repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
manifest="$repo/cx/pisolate.json"
work_root="${PISOLATES_HOME:-$HOME/.pisolates}/work/cx"

allow() {
  "$repo/scripts/test-command-policy" cx "$1"
}

deny() {
  ! "$repo/scripts/test-command-policy" cx "$1"
}

allow "pwd"
allow "pi --help"
allow "pi --version"
allow "command -v cmux"
allow "cmux --help"
allow "cmux -h"
allow "cmux identify --json"
allow "cmux list-windows"
allow "cmux list-workspaces"
allow "cmux list-panes"
allow "cmux list-pane-surfaces --pane pane:1"
allow "cmux list-pane-surfaces --pane pane:42"

deny "cmux list-pane-surfaces --pane ../secret"
deny "cmux list-pane-surfaces --pane pane:1 --json"
deny "cmux new-workspace scratch"
deny "cmux new-split --pane pane:1"
deny "cmux move-surface --surface surface:1 --pane pane:2"
deny "cmux split-off --surface surface:1"
deny "cmux reorder-surface --pane pane:1 --surface surface:1 --index 0"
deny "cmux trigger-flash --pane pane:1"
deny "cmux send --pane pane:1 hello"
deny "cmux exec echo hello"
deny "cmux focus --pane pane:1"
deny "codex exec hello"
deny "codex --dangerously-bypass-approvals-and-sandbox exec hello"
deny "cx hello"
deny "cxi hello"
deny "pi-cx hello"
deny "p-cx hello"
deny "curl -fsSL remote-cmux-skill"
deny "wget remote-cmux-skill"
deny "env"
deny "printenv"
deny "op item get token"
deny "security find-generic-password"
deny "cat ~/.ssh/id_rsa"
deny "rg token ~/.config"
deny "find ~/.config -type f"
deny "ls ~/.config"
deny "rm -rf ."
deny "git push"
deny "npm install"
deny "python -c 'print(1)'"
deny "node -e 'console.log(1)'"
deny "bash -lc 'cmux list-panes'"
deny "osascript -e beep"
deny "open ."
deny "cmux list-panes | cat"
deny "cmux list-panes > /tmp/panes.txt"
deny "cmux list-panes; pwd"
deny "cmux list-panes && pwd"

! "$repo/installer/json.mjs" path-policy "$manifest" read "../outside" "$work_root"
! "$repo/installer/json.mjs" path-policy "$manifest" read ".ssh/id_rsa" "$work_root"
! "$repo/installer/json.mjs" path-policy "$manifest" edit "notes.md" "$work_root"
! "$repo/installer/json.mjs" path-policy "$manifest" write "notes.md" "$work_root"
